### ISSUE TITLE
Add convenience to clear the whole cache

### ISSUE THREAD

**Issue by hpique** [Haneke/Haneke#15]
Currently there is no convenience method to clear the whole cache. In the meantime:

```
HNKCache *cache = [[HNKCache sharedCache];
cache.formats enumerateKeysAndObjectsUsingBlock:^(NSString *name, id obj, BOOL *stop) {
    [cache clearFormatNamed:name];
}];
```

**Comment by fraggle222** [comment]
removeAllImages does not remove images unless the format is first registered. So we don't have a way to clear the diskCache when the application loads.

**Comment by bdorfman** [comment]
I would recommend using Foursquare's fork. I added an actual removeAllImages and fixed a ton of other features. This main branch hasn't been updated in over a year.
