### ISSUE TITLE
size looks like a mandatory property on HNKCacheFormat

### ISSUE THREAD

**Issue by amarcadet** [Haneke/Haneke#55]
Hi,

I have same images displayed in two different formats: the first in a list (320x165) and the second in the detail (320x320).

It looks like the current implementation requires a `size` to be set on `HNKCacheFormat`.
I don't want to download each images two times and the "auto" behavior doesn't fit my requirements as it will create two folders.

I have made it work using the biggest size (320x320) but I was wondering if there could be side effects doing this.
Do you any advice / solution / bugfix?

Thanks for your help

**Comment by bdorfman** [comment]
If you set your format's scaleMode to HNKScaleModeNone, then the size property is ignored. That is what we do for our "generic" format that just saves the images at their native size. Not clear if that totally solves your issue, but I hope that helps!

**Comment by amarcadet** [comment]
Works perfectly!

Thanks for the tip!
