### ISSUE TITLE
Frequent crashing on simulator (iOS 8.1)

### ISSUE THREAD

**Issue by seenickcode** [Haneke/Haneke#63]
Not sure what's going on but the same Haneke method crashes every other time I launch my app with the simulator.  

Here is a screenshot

![screen shot 2015-02-06 at 10 16 12 am](https://cloud.githubusercontent.com/assets/75833/6081650/4d8b4f82-ade9-11e4-9562-51e8e6d56dad.png)

Thanks,

**Comment by francosolerio** [comment]
I think you're submitting the issue on the wrong repo. This is Haneke (obj-c), the code fragment in your screenshot is from HanekeSwift. 

I might be wrong, but that could be the same bug reported in this issue: https://github.com/Haneke/HanekeSwift/issues/115

**Comment by seenickcode** [comment]
My apologies. Thank you @francosolerio
