### ISSUE TITLE
Shared.imageCache.removeAll() not working ?

### ISSUE THREAD

**Issue by ollydbgz** [Haneke/Haneke#70]
I'm using Shared.imageCache.removeAll() to delete all memory&disk cache

But not working. Image should't show on UIImage because I'm delete that image from server.

Thank you.

**Comment by hamzaozturk** [comment]
Did you find anything about this topic? I have the same issue when i try to remove all images.

**Comment by ollydbgz** [comment]
I'm try to remove cache from NSURLCache and now my problem is resolved.
